### PR TITLE
Simplify class defaults and add a selected state

### PR DESCRIPTION
**Pull request by robojack**
I've added an option so it's possible to style Selectasaur after a user has interacted with it. Might need a bit more refinement to remove the `selected` state if the default option is re-selected.

I also simplified the class names for the various states (hover, focus, et cetera). Willing to discuss this change if you don't feel right about it.

### CODE REVIEW

**Comment by keighl** [comment]
> I've added an option so it's possible to style Selectasaur after a user has interacted with it. Might need a bit more refinement to remove the selected state if the default option is re-selected.

Cool, I like. Would it make more sense to have it look for an empty value to determine if an item is selected or not (instead of "is it the first option")? 

> I also simplified the class names for the various states (hover, focus, et cetera). Willing to discuss this change if you don't feel right about it.

You probably know my view on this. I love namespacing. I don't like classes like `.active` since they will probably conflict with the average CSSer's code. What about just changing the class namespace to `.ss-*` to make it less verbose?

**Comment by robojack** [comment]
For the selected state, I would agree that checking for a value instead of the first option would make more sense. More often than not the default option will be valueless. In cases where this is not true, the developer can ignore defining selected state styles.

Regarding class names, limiting verbosity is a good compromise. I understand that catering to an average front end engineer is a better approach.

I'll make a few updates and update this pull request.

**Comment by keighl** [comment]
Hotness!

On Wed, Jan 21, 2015 at 1:20 PM, Caley Jack <notifications@github.com>
wrote:

> For the selected state, I would agree that checking for a value instead of
> the first option would make more sense. More often than not the default
> option will be valueless. In cases where this is not true, the developer
> can ignore defining selected state styles.
>
> Regarding class names, limiting verbosity is a good compromise. I
> understand that catering to an average front end engineer is a better
> approach.
>
> I'll make a few updates and update this pull request.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/keighl/selectasaur/pull/2#issuecomment-70891613>.
>



-- 

Kyle Truscott
Sea Salt
+15082653032

**Comment by robojack** [comment]
The selected state is now based on the value attribute. Something I didn't realize though, if the option element is missing the value attribute, the value defaults to the text content. Think we should update the examples to reflect that the value attribute should be set?

**Pull request merged**
